%% Measurement-error sensitivity: add Gaussian noise to observed L
%
% Reviewer 1 asked for measurement-error sensitivity for the EEG-severity
% proxy L_t. Here we load the baseline observational data (trialData0.csv
% generated by a0_GenerateTrialData.m), perturb the L column with
% N(0, sigma^2) at a grid of sigmas (clamped to [0, 1] since L is a
% nonnegative probability-like quantity), then re-run the g-formula
% pipeline on the perturbed data and report the recovered ATE.
%
% We treat the ground-truth ATE as the RCT ATE from trialData1.csv (which
% is by construction +14.8% in the baseline DGP).
%
% Run from the CICADAS repo root (or from this directory; script adds
% the repo paths).

clear; clc; format compact;
script_dir = fileparts(mfilename('fullpath'));
repo_root  = fileparts(fileparts(script_dir));
addpath(repo_root);
addpath(genpath(fullfile(repo_root, 'CICADA_FIGURES')));

T0_base = readtable(fullfile(repo_root, 'trialData0.csv'));
T1      = readtable(fullfile(repo_root, 'trialData1.csv'));
[s0_true, s1_true] = fcnPlotKM(T1); close all;
ate_truth = s1_true(end) - s0_true(end);
fprintf('Baseline RCT truth ATE = %.3f\n', ate_truth);

sigma_vals = [0, 0.01, 0.025, 0.05, 0.1, 0.2];
n_seeds    = 3;

ate_obs   = nan(length(sigma_vals), n_seeds);
bias_obs  = nan(length(sigma_vals), n_seeds);
t_all = tic;

for is = 1:length(sigma_vals)
    sigma = sigma_vals(is);
    for k = 1:n_seeds
        rng(100 + 10*is + k);
        T0 = T0_base;
        T0.L = max(0, T0.L + sigma * randn(height(T0), 1));
        writetable(T0, fullfile(repo_root, 'trialData0_noisy.csv'));

        try
            parmsY_est = fcnEstimateDeathParms(T0);
            [parmsL_est, LL, AA, age_e, sofa_e, t_e] = fcnEstimateParmsL(T0);
            [ke_est, C_est, g_est] = fcnEstimateParmsPKPD(parmsL_est, LL, AA, age_e, sofa_e, t_e);

            N  = length(unique(T0.sid));
            dt = 2; t = 0:dt:168;
            parmsControl = [10, 50]; th = 0.1;
            L0_est = fcnGenerateStochasticTrajectories(t, parmsL_est, N);
            T1_est = fcnSimulate_N_Patients(N, 1, 0.5*ones(1, N), th, C_est, g_est, ...
                                             ke_est, L0_est, parmsControl, parmsY_est, ...
                                             zeros(1, 6), T0.age(1:N), T0.sofa(1:N));
            [s0_gf, s1_gf] = fcnPlotKM(T1_est); close all;
            ate_obs(is, k)  = s1_gf(end) - s0_gf(end);
            bias_obs(is, k) = ate_obs(is, k) - ate_truth;
        catch ME
            fprintf('  [WARN] sigma=%.3f seed=%d: %s\n', sigma, k, ME.message);
        end
        fprintf('sigma=%.3f seed=%d: ATE=%.3f, bias=%+.3f\n', ...
                sigma, k, ate_obs(is, k), bias_obs(is, k));
    end
end

fprintf('\nSweep total: %.1f min\n', toc(t_all)/60);

delete(fullfile(repo_root, 'trialData0_noisy.csv'));

ate_mean  = nanmean(ate_obs, 2);
ate_sd    = nanstd(ate_obs, 0, 2);
bias_mean = nanmean(bias_obs, 2);

out_file = fullfile(script_dir, 'measurement_error_results.mat');
save(out_file, 'sigma_vals','ate_obs','bias_obs','ate_mean','ate_sd','bias_mean','ate_truth','n_seeds');
fprintf('Saved %s\n', out_file);

%% Figure
figure(1); clf;
errorbar(sigma_vals, 100*ate_mean, 100*ate_sd, 'o-', 'LineWidth', 2, 'MarkerSize', 8);
yline(100*ate_truth, 'r--', 'LineWidth', 1.5, 'Label', sprintf('RCT truth = %.1f%%', 100*ate_truth));
xlabel('Gaussian noise SD on L_t (disease-severity proxy)');
ylabel('G-formula ATE at 168 h (percentage points)');
title(sprintf('Measurement-error sensitivity of the CICADAS g-formula\nmean \x00B1 SD across %d seeds per \\sigma', n_seeds));
grid on; set(gca, 'FontSize', 11);
set(gcf, 'Units','inches', 'Position',[1 1 7 5]);
set(gcf, 'PaperUnits','inches', 'PaperSize',[7 5], 'PaperPosition',[0 0 7 5]);
print(gcf, fullfile(script_dir, 'Fig_measurement_error.pdf'), '-dpdf', '-r300');

%% Text summary
fid = fopen(fullfile(script_dir, 'measurement_error_summary.txt'), 'w');
fprintf(fid, 'Measurement-error sensitivity (L_t perturbed with N(0, sigma^2))\n');
fprintf(fid, 'N seeds per sigma: %d\n', n_seeds);
fprintf(fid, 'RCT truth ATE: %+.3f\n\n', ate_truth);
fprintf(fid, '%-8s %-12s %-12s %-12s\n', 'sigma', 'mean ATE', 'SD ATE', 'mean bias');
for is = 1:length(sigma_vals)
    fprintf(fid, '%-8.3f %+12.3f %12.3f %+12.3f\n', ...
            sigma_vals(is), ate_mean(is), ate_sd(is), bias_mean(is));
end
fclose(fid);
fprintf('Saved text summary.\n');
